import SwiftUI

struct CoachView: View {
    @EnvironmentObject var model: AppModel
    @State private var loading = false
    @State private var error: String?
    @State private var message: String? = SharedStore.coachMessage

    private var hasKey: Bool { AICoach.apiKey != nil }

    var body: some View {
        Screen {
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    HStack {
                        Text("Dr. Brain").font(.display(34)).foregroundStyle(.white)
                        Spacer()
                        Image(systemName: "stethoscope").font(.title2).foregroundStyle(Theme.violet)
                    }.padding(.top, 8)

                    Card {
                        HStack(alignment: .top, spacing: 14) {
                            BrainView(rot: model.snap.rot, glow: false).frame(width: 64, height: 64)
                            VStack(alignment: .leading, spacing: 6) {
                                Text(todayLabel).font(.system(.caption, design: .rounded).weight(.heavy)).tracking(1).foregroundStyle(Theme.textDim)
                                if loading {
                                    HStack(spacing: 8) { ProgressView().tint(Theme.violet); Text("Examining the brain…").foregroundStyle(Theme.textDim) }
                                        .font(.system(.subheadline, design: .rounded))
                                } else {
                                    Text(message ?? Roasts.line(for: model.snap, language: SharedStore.coachLanguage))
                                        .font(.system(.body, design: .rounded)).foregroundStyle(.white)
                                }
                            }
                        }
                        if let error {
                            Text(error).font(.system(.footnote, design: .rounded)).foregroundStyle(Theme.pink)
                        }
                    }

                    PrimaryButton(title: hasKey ? "New verdict" : "New verdict (offline)", symbol: "sparkles", tint: Theme.violet) { Task { await ask() } }
                        .disabled(loading).opacity(loading ? 0.6 : 1)

                    Card {
                        HStack {
                            Image(systemName: hasKey ? "key.fill" : "key.slash").foregroundStyle(hasKey ? Theme.acid : Theme.pink)
                            Text(hasKey ? "Claude connected" : "Claude not connected")
                                .font(.system(.subheadline, design: .rounded).weight(.bold)).foregroundStyle(.white)
                            Spacer()
                            Button("Settings") { model.tab = .settings }.font(.system(.subheadline, design: .rounded).weight(.bold))
                        }
                        Text(hasKey ? "Verdicts are generated by Claude from your last 7 days. Your app names never leave the phone — only minute counts."
                                    : "Add an Anthropic API key in Settings for personalised roasts. Until then you get the house blend.")
                            .font(.system(.footnote, design: .rounded)).foregroundStyle(Theme.textDim)
                    }

                    Card {
                        SectionTitle(text: "What Dr. Brain sees")
                        ForEach(SharedStore.recentDays(7), id: \.day) { d in
                            HStack {
                                Text(d.day, format: .dateTime.weekday(.abbreviated)).font(.system(.subheadline, design: .rounded)).foregroundStyle(Theme.textDim)
                                    .frame(width: 44, alignment: .leading)
                                GeometryReader { geo in
                                    ZStack(alignment: .leading) {
                                        Capsule().fill(.white.opacity(0.06))
                                        Capsule().fill(d.minutes > model.snap.limit ? Theme.pink : Theme.acid)
                                            .frame(width: max(4, geo.size.width * min(1, Double(d.minutes) / Double(max(model.snap.limit, 1) * 2))))
                                    }
                                }.frame(height: 8)
                                Text(d.minutes.asDuration).font(.system(.subheadline, design: .rounded).weight(.semibold).monospacedDigit())
                                    .foregroundStyle(.white).frame(width: 56, alignment: .trailing)
                            }
                        }
                    }
                }
                .padding(.horizontal, 18).padding(.bottom, 30)
            }
        }
        .onAppear {
            message = SharedStore.coachMessage
            // Auto-refresh once a day.
            if let d = SharedStore.coachDate, Calendar.current.isDateInToday(d) { return }
            Task { await ask() }
        }
    }

    private var todayLabel: String {
        if let d = SharedStore.coachDate { return "VERDICT · \(d.formatted(date: .omitted, time: .shortened))" }
        return "VERDICT"
    }

    private func ask() async {
        loading = true; error = nil
        defer { loading = false }
        do {
            let text = try await AICoach.verdict(snap: model.snap, days: SharedStore.recentDays(7), language: SharedStore.coachLanguage)
            message = text
            SharedStore.coachMessage = text
            SharedStore.coachDate = Date()
            model.refresh()
        } catch {
            self.error = "Claude: \(error.localizedDescription)"
            let fallback = Roasts.line(for: model.snap, language: SharedStore.coachLanguage)
            message = fallback
            SharedStore.coachMessage = fallback
            SharedStore.coachDate = Date()
            model.refresh()
        }
    }
}
