import Foundation

/// "Dr. Brain": a short daily verdict generated by Claude from your usage, with an offline fallback.
enum AICoach {
    static let keychainKey = "anthropicApiKey"
    static var apiKey: String? { Keychain.get(keychainKey).flatMap { $0.isEmpty ? nil : $0 } }

    struct APIError: LocalizedError {
        let message: String
        var errorDescription: String? { message }
    }

    static func verdict(snap: RotSnapshot, days: [(day: Date, minutes: Int)], language: String) async throws -> String {
        guard let key = apiKey else { return Roasts.line(for: snap, language: language) }

        let df = DateFormatter(); df.dateFormat = "EEE"
        let hist = days.map { "\(df.string(from: $0.day)): \($0.minutes) min" }.joined(separator: ", ")
        let lang = language == "cs" ? "Czech (informal, tykání)" : "English"
        let system = """
        You are Dr. Brain, the in-app coach of "Brainrot", an iOS app that tracks short-form video scrolling \
        (Instagram Reels, TikTok, YouTube Shorts) and shows the user's brain rotting as usage grows. \
        Write in \(lang). Voice: dry, funny, a little savage, never cruel; one concrete, doable suggestion. \
        2–3 sentences, max 260 characters. No emojis, no hashtags, no preamble, no quotes.
        """
        let user = """
        Today: \(snap.minutes) min of \(snap.limit) min limit (\(snap.rotPercent)% rotten, stage: \(snap.stage.title)). \
        Mode: \(snap.mode.title). Streak of days under limit: \(snap.streak). Challenges completed: \(snap.challengesDone). \
        Last 7 days: \(hist). Time now: \(DateFormatter.localizedString(from: Date(), dateStyle: .none, timeStyle: .short)). \
        Give today's verdict.
        """
        let body: [String: Any] = [
            "model": "claude-opus-5",
            "max_tokens": 1024,   // deliberately short output
            "output_config": ["effort": "low"],
            "system": system,
            "messages": [["role": "user", "content": user]]
        ]
        var req = URLRequest(url: URL(string: "https://api.anthropic.com/v1/messages")!)
        req.httpMethod = "POST"
        req.timeoutInterval = 60
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue(key, forHTTPHeaderField: "x-api-key")
        req.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
        req.httpBody = try JSONSerialization.data(withJSONObject: body)

        let (data, response) = try await URLSession.shared.data(for: req)
        guard let http = response as? HTTPURLResponse else { throw APIError(message: "No response") }
        let json = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
        guard http.statusCode == 200 else {
            let msg = ((json?["error"] as? [String: Any])?["message"] as? String) ?? "HTTP \(http.statusCode)"
            throw APIError(message: msg)
        }
        if let stop = json?["stop_reason"] as? String, stop == "refusal" {
            return Roasts.line(for: snap, language: language)
        }
        let text = ((json?["content"] as? [[String: Any]]) ?? [])
            .compactMap { $0["type"] as? String == "text" ? $0["text"] as? String : nil }
            .joined()
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { throw APIError(message: "Empty response") }
        return text
    }
}
